// Import Counter component to use in this page's contents
import Counter from "@/components/Counter";

import Head from "next/head"; // Used to inject metadata elements into the html <head> tag
import { Geist, Geist_Mono } from "next/font/google"; // Loads necessary font libraries

// Reuse Home CSS module for page styling. Primary page structure remains the same across all pages.
import styles from "@/styles/Home.module.css";

// Grab Geist Sans and Geist Mono CSS modules from library functions to use as variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function CounterPage() {
  
  /*
    
    The Head component is imported from node_modules/next folder
    It is used to inject metadata elements into the html <head> tag
    such as title, meta, favicons, viewport scaling, etc.
    
    Counter component is declared with an initial value of 0.
    This prop will be used within the component's code to set up state for that variable.
    
  */
  return (
    <>
      <Head>
        <title>CPAN144 Assignment 1: Counter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={styles.main}>
          <div className={styles.intro}>
            <h1>Counter</h1>
            <p>This is a page displaying the use of a <b>stateful counter component</b>, along with <b>conditional rendering</b> examples.</p>
            <Counter initialValue={0}/>
          </div>
        </main>
      </div>
    </>
  );
}