import Counter from "@/components/Counter";
import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { ListData } from "@/components/ListData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function CounterPage() {
  return (
    <>
      <Head>
        <title>CPAN144 Assignment 1: Counter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={styles.main}>
          <div className={styles.intro}>
            <h1>List Items</h1>
            <p>This is a page displaying the use of a stateful counter component, along with conditional rendering usage.</p>
            <Counter initialValue={0}/>
          </div>
        </main>
      </div>
    </>
  );
}