import List from "@/components/List"; // Imports List component to use in page
import Head from "next/head"; // Used to inject metadata elements into the html <head> tag
import { Geist, Geist_Mono } from "next/font/google"; // Loads necessary font libraries

// Reuse Home CSS module for page styling. Primary page structure remains the same across all pages.
import styles from "@/styles/Home.module.css";

// JS array that only serves as data for list items (in {object form}).
// Will be used as the initialValue prop in <List/> component
import { ListData } from "@/components/ListData";

// Grab Geist Sans and Geist Mono CSS modules from library functions to use as variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function ListItems() {
  /*
    
    The Head component is imported from node_modules/next folder
    It is used to inject metadata elements into the html <head> tag
    such as title, meta, favicons, viewport scaling, etc.
    
    List component is declared with an initial value of ListData.
    This prop will be used within the component's code to set up state for that variable.
    That state will be used for a Details section showing more information about the selected list item.
    
  */
  return (
    <>
      <Head>
        <title>CPAN144 Assignment 1: List Items</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={styles.main}>
          <div className={styles.intro}>
            <h1>List Items</h1>
            <p>This is a page displaying the use of list items, along with details below of selected list items to make use of conditional rendering and stateful components.</p>
            <List initialValue={ListData}/>
          </div>
        </main>
      </div>
    </>
  );
}
