import Head from "next/head"; // Used to inject metadata elements into the html <head> tag
import { Geist, Geist_Mono } from "next/font/google"; // Loads necessary font libraries
import styles from "@/styles/Home.module.css"; // Use Home CSS module for homepage styling.

// Grab Geist Sans and Geist Mono CSS modules from library functions to use as variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/* This is the homepage of the assignment.
It does not have any actual components, but
it advises the user to explore the Navbar at the top
to view the other pages and their components.

(In case you're wondering, the Navbar is being
supplied through @/pages/_app.js) */
export default function Home() {
  return (
    <>
      <Head>
        <title>CPAN144 Assignment 1: Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}>
        <main className={styles.main}>
          <div className={styles.intro}>
            <h1>Welcome!</h1>
            <p>This is the homepage of the assignment.<br></br>
            <b>Check the navigation bar</b> up top to view the different pages,
            components and React concepts applied within the assignment.</p>
          </div>
        </main>
      </div>
    </>
  );
}
